version: '3'

services:
  app:
    build: .
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: npm run start:prod

  db:
    image: postgres:14.3
    container_name: loteproduccion
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_prod:/var/lib/postgresql/data




# version: '3'

# services:
#   db: 
#     image: postgres:14.3
#     restart: always
#     ports:
#       - "5432:5432"
#     environment: 
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     container_name: loteDesarrollo
#     volumes:
#       - ./postgres:/var/lib/postgresql/data      
